# Local Development Configuration for EZLogs Agent
# Use this for testing with Rails EZLogs collector

# Server configuration
server:
  host: "0.0.0.0"
  port: 9001          # Use different port to avoid conflicts

# Buffer configuration
buffer:
  max_size: 1000         # Smaller buffer for development
  batch_size: 50         # Smaller batches for faster testing
  flush_interval: "2s"   # Faster flushing for development

# Collector configuration - RAILS APPLICATION API
collector:
  base_url: "http://localhost:3000/api/events"       # Your Rails app base URL
  api_key: "17383f0a488c6bb320d883307da658c2644a036984f262a04bb6d3ea928fb152"                  # Development API key  
  timeout: "10s"                          # Shorter timeout for local
  
  # HTTP transport settings
  max_idle_conns: 10
  max_idle_conns_per_host: 5
  idle_conn_timeout: "30s"
  
  # Circuit breaker settings
  circuit_breaker:
    failure_threshold: 5
    reset_timeout: "30s"
    half_open_max_requests: 3

# Security configuration
security:
  allowed_hosts:
    - "127.0.0.1"
    - "::1"
    - "localhost"
  auto_detect_pii: true
  sensitive_fields:
    - "password"
    - "token" 
    - "api_key"
    - "secret"

# Health check configuration
health:
  enabled: true
  port: 8081

# Metrics configuration  
metrics:
  enabled: true
  port: 9091

# Logging configuration
logging:
  level: "debug"
  format: "json" 