# Local Development Configuration for EZLogs Agent (compatible with main.go)
# Extracted from configs/local-dev.yaml and flattened for main.go compatibility

listen: "0.0.0.0:9050"
endpoint: "http://localhost:3000/api/events"
api_key: "17383f0a488c6bb320d883307da658c2644a036984f262a04bb6d3ea928fb152"
interval: 2s
batch: 50
queue: 1000 