# Real-Time Development Configuration - Minimal Delays
# Use this when you need immediate event forwarding for testing

listen: "0.0.0.0:9050"
endpoint: "http://localhost:3000/api/events"
api_key: "17383f0a488c6bb320d883307da658c2644a036984f262a04bb6d3ea928fb152"
interval: 100ms    # Send every 100ms instead of 2s
batch: 1          # Send immediately after receiving 1 event
queue: 1000 